name = "triangle-live-music"
compatibility_date = "2025-10-19"
main = "worker.js"

[[r2_buckets]]
binding = "DATA_BUCKET"
bucket_name = "triangle-live-music-data"

[assets]
directory = "./"
exclude = ["*.toml", "*.conf", "Dockerfile", "docker-compose.yml", ".dockerignore", "serve.py"]
